### PR TITLE
fix: improve validation of apps and display of errors

### LINKED ISSUE #65: When using the same URL as another app, there is no validation but the creation fails
Add some validation on the app_url_key constraint for application urls

### PR DESCRIPTION
**Pull request by spaenleh**
In this PR:
- fix #65 app url duplicate constraint error with early feedback to user
- improve error display with button alignment

New feedback on unique constraint violation:

https://github.com/user-attachments/assets/b3fe48c2-53f5-4c0c-a23e-d7316a894c65

Below are some videos showing the difference:

Before:

https://github.com/user-attachments/assets/a90c3fd3-b945-44cf-94f1-2ec4bb925b59

After:

https://github.com/user-attachments/assets/b5c8768d-d243-4b71-8688-5bbe4e37734c

### CODE REVIEW

File: lib/admin/apps/app_instance.ex [hunk 1]
```diff
@@ -24,20 +24,19 @@ defmodule Admin.Apps.AppInstance do
   def update_changeset(app_instance, attrs) do
     app_instance
     |> cast(attrs, [:name, :description, :url, :thumbnail, :key])
+    |> unsafe_validate_unique(:url, Admin.Repo,
+      message: "URL already used in another app. URLs must be unique."
```
Comment (pyphilia) [inline lib/admin/apps/app_instance.ex]:
```suggestion
      message: "This URL is already used for another app. URLs must be unique."
```
