### PR TITLE
fix: use hosts of real deployments

### LINKED ISSUE #55: Publication: Player and library buttons are broken?
Buttons are not contextual to the item.

Also would we consider opening a new tab for those buttons?

https://github.com/user-attachments/assets/047a74be-639b-4c48-876f-32f1ffd18782

### PR DESCRIPTION
**Pull request by spaenleh**
In this PR:
- fix #55

### CODE REVIEW

File: lib/admin/platforms.ex [hunk 1]
```diff
@@ -0,0 +1,17 @@
+defmodule Admin.Platforms do
+  @moduledoc """
+  Generate platform URLs.
+  """
+
+  defp base_host, do: Application.get_env(:admin, :base_host)
+
+  def get_url(:library, item_id) do
```
Comment (pyphilia) [inline lib/admin/platforms.ex]: Should you check item_id validity? ie. empty string, nil, etc?
Applies for all functions there.

**Review by pyphilia — APPROVED** [review]

File: lib/admin/platforms.ex (hunk 1 above)
Comment (spaenleh) [reply lib/admin/platforms.ex]: I added tests. 

I can add a guard to the function, so that it does not match if it is not a string. But what should we do if it does not match ? should we provide a default to the library home ? return an empty string ? let it crash when called ?
